name: AEM Environment Keeper

on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env:
          - DEV
          - STAGE
          - PROD

    steps:
      - name: Select URL
        run: |
          if [ "${{ matrix.env }}" = "DEV" ]; then
            echo "AEM_URL=${{ secrets.AEM_DEV_URL }}" >> $GITHUB_ENV
          elif [ "${{ matrix.env }}" = "STAGE" ]; then
            echo "AEM_URL=${{ secrets.AEM_STAGE_URL }}" >> $GITHUB_ENV
          else
            echo "AEM_URL=${{ secrets.AEM_PROD_URL }}" >> $GITHUB_ENV
          fi

      - name: Ping AEM
        run: |
          echo "Pinging $AEM_URL"

          STATUS=$(curl \
            --silent \
            --output /dev/null \
            --write-out "%{http_code}" \
            "$AEM_URL")

          echo "${{ matrix.env }} Status: $STATUS"

          if [ "$STATUS" != "200" ]; then
            echo "Failed for $AEM_URL"
            exit 1
          fi
